//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueTrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerContact
    {
        public string CustomerID { get; set; }
        public string CustomeName { get; set; }
        public string TelephoneNo { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
